name: Docker Image CI

on:
  workflow_dispatch:  # 👈 Only runs when manually triggered

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag torgman:$(date +%s)
